baseURL: "https://xiaoqiaotq.github.io"
languageCode: "zh-cn"
title: "xiaoqiaotq"
theme: "PaperMod"
paginate: 5
menu:
  main:
    - name: 总览
      url: archives
      weight: 5
    - name: 搜索
      url: search/
      weight: 10
#    - identifier: 分类
#      name: 分类
#      url: /categories/
#      weight: 10
    - identifier: 标签
      name: 标签
      url: /tags/
      weight: 20
#    - identifier: example
#      name: example.org
#      url: https://example.org
#      weight: 30
#    - identifier: home
#      name: 主页
#      url: /posts/home/
#      weight: 40

params:
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog
  socialIcons:
    - name: github
      url: "https://github.com/xiaoqiaotq"

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/64*64.ico"
    favicon16x16: "/16*16.ico"
    favicon32x32: "/32*32.ico"
    apple_touch_icon: "/64*64.ico"
    safari_pinned_tab: "/64*64.ico"

outputs:
  home:
    - HTML
    - RSS
    - JSON