baseURL: "https://xiaoqiaotq.github.io"
languageCode: "zh-cn"
title: "xiaoqiaotq"
theme: "PaperMod"
menu:
  main:
    - identifier: 分类
      name: 分类
      url: /categories/
      weight: 10
    - identifier: 标签
      name: 标签
      url: /tags/
      weight: 20
#    - identifier: example
#      name: example.org
#      url: https://example.org
#      weight: 30
#    - identifier: home
#      name: 主页
#      url: /posts/home/
#      weight: 40